title: "Yasmani Vargas"
#logo: /assets/img/headshot_circle.png
description: Doctor en Economía y Políticas Públicas <br> Universidad Nacional del Altiplano
#show_downloads: true
theme: jekyll-theme-minimal
